[package]
name = "step_02"
version = "0.1.0"

edition = "2024"

[dependencies]


# [[bin]]
# name = "my_app"      # name of the executable (my_app.exe under WIN11)
# path = "src/main.rs"

# [lib]
# name = "my_super_lib" # name of the lib (libmy_super_lib.rlib under WIN11)
# path = "src/lib.rs"
